version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: chat_serve
        ports:
            - "9001:9000"
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/app/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - chat-test

    webserver:
        image: nginx:alpine
        container_name: nginx-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - chat-test

    db:
        image: mysql:8.0
        restart: unless-stopped
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        tty: true
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: chat-lv
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_PASSWORD: admin
            MYSQL_USER: user
            MYSQL_ROOT_HOST: '%'
        ports:
            - "3310:3306"
        container_name: chat_db
        networks:
            - chat-test

    vite:
        image: node:18
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "5173:5173"
        command: npm run dev
        container_name: chat_vite
        networks:
            - chat-test

volumes:
    db-data:
        driver: local
networks:
    chat-test:
        driver: bridge
        external: true
